name: myenv
channels:
  - defaults
dependencies:
  - python=3.7
  - scikit-learn
  - statsmodels
  - pip
  - pip:
      - pmdarima
      - azureml-sdk
      - azureml-dataset-runtime[fuse, pandas]
      - azureml-defaults
      - joblib
      - scikit-learn
      - matplotlib


